# Generated by Django 4.2.10 on 2024-02-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_studentsmodel_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('salary', models.FloatField(blank=True, default=0.0)),
                ('department', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
