# Generated by Django 4.2.10 on 2024-03-12 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_playermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=115, null=True)),
                ('gender', models.CharField(max_length=115, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=115, null=True)),
                ('duration', models.IntegerField()),
                ('singer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song', to='app_api.singer')),
            ],
        ),
    ]
